# Generated by Django 5.0.6 on 2024-06-02 04:40

import app.bot.middlewares.user.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveBigIntegerField(db_index=True, default=None, null=True, verbose_name='Telegram ID')),
                ('tg_username', models.TextField(default=None, null=True, verbose_name='Логин Telegram')),
                ('tg_first_name', models.TextField(default=None, null=True, verbose_name='имя')),
                ('tg_last_name', models.TextField(default=None, null=True, verbose_name='фамилия')),
                ('dialog', models.TextField(default='start')),
                ('is_active', models.BooleanField(default=True, help_text='Если данное поле выключено, то данный пользователь считается забаненым', verbose_name='активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='сотрудник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.bot.middlewares.user.mixin.TelegramUser),
        ),
    ]
